GET http://localhost:8000/member/member/count
Accept: application/json

###

###
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "15000000112"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "15000000112",
  "code": "8888"
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("token", response.body.content.token);
%}